### ISSUE TITLE
In Inline-Content with option "closeBtnInside=True" the Close Button is displayed twice "Inside" + "Outside"

### ISSUE THREAD

**Issue by wenglor-IT** [jonathanheilmann/ext-jh_magnificpopup#46] opened 2016-11-16 08:32 UTC
In the following context, the "Close"-button is displayed twice "Inside" + "Outside":
•Display typ: "Inline Content"
•Link typ : "Text"
•Method: "Ajax"   <-------- !!!
•Magnific Popup -> closeBrnInside : true

We are using Version 0.6.4 (T3 6.2.x)

**Comment by jonathanheilmann** [comment] 2016-11-16 08:58
Do you have a non working example for this issue, too?

**Comment by wenglor-IT** [comment] 2016-11-16 09:25
I created a hidden page:
https://www.wenglor.com/index.php?id=1177&L=1

**Comment by jonathanheilmann** [comment] 2016-11-16 11:31
Is this issue related to a special browser? Because I'm seeing the button just once (tested in Edge and Chrome): 
![www wenglor com-index php-id 1177 l 1](https://cloud.githubusercontent.com/assets/2504896/20345673/8d543e08-abf8-11e6-9848-6d4fce5ad52c.png)

**Comment by wenglor-IT** [comment] 2016-11-16 11:53
![image](https://cloud.githubusercontent.com/assets/20818559/20346272/7940e314-abfb-11e6-86a2-5f2c87f816c1.png)

We have the problem with InternetExplorer and EDGE.
There is no problem with Chrome and Firefox..

**Comment by jonathanheilmann** [comment] 2016-11-18 14:28
Sorry, I cannot see the second icon neither in Internet Explorer 11.0.36 nor in Edge 25
Maybe you could provide the rendered html as attachment?

**Comment by wenglor-IT** [comment] 2016-11-21 07:56
![image](https://cloud.githubusercontent.com/assets/20818559/20474672/fb29ceac-afc7-11e6-883e-50dc5ee6c1eb.png)

Here the html as initial loaded
[Seite1176_Quelltext.html.txt](https://github.com/jonathanheilmann/ext-jh_magnificpopup/files/602950/Seite1176_Quelltext.html.txt)

Here the html from the DOM Explorer, with popup in front:
[Seite1176_DOM_Explorer.html.txt](https://github.com/jonathanheilmann/ext-jh_magnificpopup/files/602952/Seite1176_DOM_Explorer.html.txt)

**Comment by jonathanheilmann** [comment] 2016-11-23 15:47
That's really strange and I would suggest an IE/EDGE bug.
A link tag must not contain any data and is an empty element. There is no code in this extension and Magnific Popup adding any content in a link tag. 
I'm sorry, I've no idea on how to fix this :/

**Comment by TrueType** [comment] 2018-06-18 14:04
You may close this ticket(s) I guess. Multiple close buttons may have come from the non-working disableAllHeaderCode=1 in inline/setup.txt (config key was missing). This resulted in a full page coming with the AJAX call which then was misinterpreted by $() => multiple nodes. Close buttons then showed up many times in e.g. the `<base>` tag and else.

**Comment by jonathanheilmann** [comment] 2018-06-23 15:03
@TrueType this could be the cause of the trouble, and thus should be resolved since commit on May 14, 2017 (https://github.com/jonathanheilmann/ext-jh_magnificpopup/commit/dc1e60f81b17ea1636a26f0d24431016cbb30b28#diff-2b8cc182102235392afd86708d40b766)
Thank you very much!

If this is still an issue, please open a new github issue.

**Closed as completed by jonathanheilmann** 2018-06-23 15:03 UTC
