### ISSUE TITLE
Typo3 v8 LTS supported?

### ISSUE THREAD

**Issue by finswimmer** [jonathanheilmann/ext-jh_magnificpopup#52] opened 2017-09-16 11:28 UTC
Hello,

it seems that this extension is not supported by the current LTS Release (8.7.6). Are there any plans for it?

fin swimmer

**Comment by jonathanheilmann** [comment] 2017-09-25 05:13
Hi,

there are plans, but still some issues.
I'm going to close this as an duplicate of #47 

Jonathan

**Closed as completed by jonathanheilmann** 2017-09-25 05:13 UTC
